### ISSUE TITLE
Doesn't Work!

### ISSUE THREAD

**Issue by mr-bat** [soachishti/moss.py#11]
Crashes with the log below.

```Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 159, in main
    sendToMoss()
  File "main.py", line 141, in sendToMoss
    url = moss.send()
  File "/Library/Python/2.7/site-packages/mosspy/moss.py", line 109, in send
    s.connect((self.server, self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 61] Connection refused

**Comment by soachishti** [comment]
Kindly review the comments of issue #9, hope you will find the solution. If not let us know here.

**Comment by soachishti** [comment]
I'm closing this issue because it has been inactive.
